version: "3"
services:

  app:
    image: node:alpine
    network_mode: host
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    command: node server.js

  appclient:
    image: node:alpine
    network_mode: host
    volumes:
      - ../appclient:/app/appclient
    working_dir: /app/appclient
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    command: node server.js

  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
      